DEBUG = true;

// Variables
LoadoutHash = createHashMapFromArray [
    ["cwr3_o_soldier_sl", [["CUP_arifle_AKS74","","","CUP_optic_PechenegScope",["CUP_30Rnd_545x39_AK_M",30],[],""],["CUP_launch_RPG18","","","",["CUP_RPG18_M",1],[],""],["hgun_Pistol_01_F","","","",["10Rnd_9x21_Mag",10],[],""],["CUP_U_O_RUS_Flora_2",[["ACE_fieldDressing",3],["ACE_elasticBandage",3],["ACE_packingBandage",3],["ACE_quikclot",3],["ACE_EarPlugs",1],["ACE_epinephrine",1],["ACE_morphine",1],["ACE_splint",1],["ACE_tourniquet",2],["SmokeShell",2,1]]],["cwr3_o_vest_6b2_officer",[["CUP_HandGrenade_RGD5",2,1],["CUP_30Rnd_545x39_AK_M",5,30]]],["cwr3_o_backpack_rd54",[["ACE_Canteen",1],["ACE_Humanitarian_Ration",1],["ACE_EntrenchingTool",1],["ACE_MapTools",1],["ACE_Flashlight_MX991",1]]],"cwr3_o_headgear_ssh68","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]],
    ["cwr3_o_soldier", [["CUP_arifle_AKS74","","","",["CUP_30Rnd_545x39_AK_M",30],[],""],["CUP_launch_RPG18","","","",["CUP_RPG18_M",1],[],""],["hgun_Pistol_01_F","","","",["10Rnd_9x21_Mag",10],[],""],["CUP_U_O_RUS_Flora_2",[["ACE_fieldDressing",3],["ACE_elasticBandage",3],["ACE_packingBandage",3],["ACE_quikclot",3],["ACE_EarPlugs",1],["ACE_epinephrine",1],["ACE_morphine",1],["ACE_splint",1],["ACE_tourniquet",2],["SmokeShell",2,1]]],["cwr3_o_vest_6b2_ak74",[["CUP_HandGrenade_RGD5",2,1],["CUP_30Rnd_545x39_AK_M",5,30]]],["cwr3_o_backpack_rd54",[["ACE_Canteen",1],["ACE_Humanitarian_Ration",1],["ACE_EntrenchingTool",1],["ACE_Flashlight_MX991",1]]],"cwr3_o_headgear_ssh68","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]],
    ["cwr3_o_soldier_gl", [["CUP_arifle_AKS74_GL_Early","","","",["CUP_30Rnd_545x39_AK_M",30],["CUP_1Rnd_HE_GP25_M",1],""],["CUP_launch_RPG18","","","",["CUP_RPG18_M",1],[],""],["hgun_Pistol_01_F","","","",["10Rnd_9x21_Mag",10],[],""],["CUP_U_O_RUS_Flora_2",[["ACE_fieldDressing",3],["ACE_elasticBandage",3],["ACE_packingBandage",3],["ACE_quikclot",3],["ACE_EarPlugs",1],["ACE_epinephrine",1],["ACE_morphine",1],["ACE_splint",1],["ACE_tourniquet",2],["SmokeShell",2,1]]],["cwr3_o_vest_6b2_gl",[["CUP_HandGrenade_RGD5",2,1],["CUP_30Rnd_545x39_AK_M",5,30],["CUP_1Rnd_HE_GP25_M",10,1],["CUP_1Rnd_SMOKE_GP25_M",2,1],["CUP_1Rnd_SmokeRed_GP25_M",2,1],["CUP_1Rnd_SmokeGreen_GP25_M",2,1]]],["cwr3_o_backpack_rd54",[["ACE_Canteen",1],["ACE_Humanitarian_Ration",1],["ACE_EntrenchingTool",1],["ACE_Flashlight_MX991",1]]],"cwr3_o_headgear_ssh68","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]],
    ["cwr3_o_soldier_at_rpg7", [["CUP_arifle_AKS74","","","",["CUP_30Rnd_545x39_AK_M",30],[],""],["CUP_launch_RPG7V","","","CUP_optic_PGO7V",["CUP_PG7V_M",1],[],""],["hgun_Pistol_01_F","","","",["10Rnd_9x21_Mag",10],[],""],["CUP_U_O_RUS_Flora_2",[["ACE_fieldDressing",3],["ACE_elasticBandage",3],["ACE_packingBandage",3],["ACE_quikclot",3],["ACE_EarPlugs",1],["ACE_epinephrine",1],["ACE_morphine",1],["ACE_splint",1],["ACE_tourniquet",2],["SmokeShell",2,1]]],["cwr3_o_vest_6b2_ak74",[["CUP_HandGrenade_RGD5",2,1],["CUP_30Rnd_545x39_AK_M",5,30]]],["cwr3_o_backpack_rpg7",[["ACE_Canteen",1],["ACE_Humanitarian_Ration",1],["ACE_EntrenchingTool",1],["ACE_Flashlight_MX991",1],["CUP_PG7V_M",2,1]]],"cwr3_o_headgear_ssh68","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]],
    ["cwr3_o_soldier_mg", [["CUP_arifle_RPK74_45","","","",["CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",45],[],""],["CUP_launch_RPG18","","","",[],[],""],["hgun_Pistol_01_F","","","",["10Rnd_9x21_Mag",10],[],""],["CUP_U_O_RUS_Flora_2",[["ACE_fieldDressing",3],["ACE_elasticBandage",3],["ACE_packingBandage",3],["ACE_quikclot",3],["ACE_EarPlugs",1],["ACE_epinephrine",1],["ACE_morphine",1],["ACE_splint",1],["ACE_tourniquet",2],["SmokeShell",2,1]]],["cwr3_o_vest_6b2_mg",[["CUP_HandGrenade_RGD5",2,1],["CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",8,45]]],["cwr3_o_backpack_rd54",[["ACE_Canteen",1],["ACE_Humanitarian_Ration",1],["ACE_EntrenchingTool",1],["ACE_Flashlight_MX991",1]]],"cwr3_o_headgear_ssh68","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]]
];